services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: softskills
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000" 
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: 12345
    depends_on:
      - db
