name: Auto Create PR

on:
  push:
    branches:
      - feature-test

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          BRANCH_NAME="auto-pr-$(date +%s)"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          gh pr create --title "Auto PR for Main" --body "Automatic PR for changes pushed to main" --base main --head $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}